import type { Product } from "./products";

export const powerOneFallbackProducts: Product[] = [
  /* ══════════════════════════════════════════════════════════════════
     1. POWER-ONE UPS — PMP SERIES (3-Phase In / 3-Phase Out, 11 kVA to 500 kVA)
     Reference: https://www.poweroneups.com/product/pmp-series
     ══════════════════════════════════════════════════════════════════ */
  {
    id: "power-one-pmp-11kva",
    name: "Power-One PMP 11kVA / 8kW 3-Phase Online UPS",
    category: "Power-One UPS",
    subcategory: "PMP Series",
    brand: "Power-One",
    series: "PMP Series",
    model: "PMP 11",
    capacity: "11 kVA / 8 kW",
    price: 0,
    rating: 4.9,
    stock: 12,
    image: "/images/products/power-one/pmp_dropdown.png",
    images: [
      "/images/products/power-one/pmp_dropdown.png",
      "/images/products/power-one/product_pmp.svg",
    ],
    tagline: "Industrial 3-Phase in / 3-Phase out true double conversion online UPS with isolation transformer.",
    description: "The Power-One PMP 11 is an industrial-grade true online double-conversion UPS system designed for critical three-phase industrial and mission-critical installations. Featuring an integrated isolation transformer, DSP digital control, wide input voltage window (305V–485V Ph-Ph), and static bypass with zero transfer time.",
    warranty: "2 Years Manufacturer Warranty",
    badges: ["Power-One Official", "3Ph In / 3Ph Out", "Pure Sine Wave", "Quote on Request"],
    specs: [
      { label: "Series", value: "PMP Series" },
      { label: "Model", value: "PMP 11" },
      { label: "Capacity Rating", value: "11 kVA / 8 kW" },
      { label: "Phase Configuration", value: "3 Phase In / 3 Phase Out (3Ph+N)" },
      { label: "Input Voltage", value: "400VAC / 415VAC (305VAC ~ 485VAC Range)" },
      { label: "Input Frequency", value: "40 Hz to 70 Hz" },
      { label: "Output Voltage", value: "380VAC / 400VAC / 415VAC (±1% Regulation)" },
      { label: "Output THD", value: "< 1% (Linear Load), < 3% (Non-linear load)" },
      { label: "Crest Factor", value: "3:1" },
      { label: "DC Bus / Battery Voltage", value: "384 VDC (12V x 32 Nos, 29~32 adjustable)" },
      { label: "Dimensions (W x D x H)", value: "405 x 656 x 817 mm" },
      { label: "Net Weight", value: "118 kg" },
    ],
    features: [
      "True double conversion online topology with built-in galvanic isolation transformer",
      "High-speed DSP (Digital Signal Processing) control architecture",
      "Wide input voltage range (305VAC ~ 485VAC) accommodating harsh Nepalese grid conditions",
      "Zero transfer time static bypass and built-in manual maintenance bypass switch",
      "High overload capability: 110% for 60 min, 125% for 10 min, 150% for 60 sec",
      "Supports VRLA SMF, Tubular, NiCad, and Lithium-Ion battery banks",
      "Parallel redundancy capability up to 8 units for enterprise scalability",
      "Comprehensive communication interfaces: RS232, RS485 MODBUS, SNMP, Dry Contacts",
    ],
    applications: [
      "Data Centers & Server Rooms",
      "Hospitals & Diagnostic Imaging (MRI, CT, Ultrasound)",
      "Industrial Automation & CNC Machinery",
      "Commercial Complexes & Financial Institutions",
      "Telecommunication Switching Centers",
    ],
    sourceUrl: "https://www.poweroneups.com/product/pmp-series",
  },
  {
    id: "power-one-pmp-15kva",
    name: "Power-One PMP 15kVA / 12kW 3-Phase Online UPS",
    category: "Power-One UPS",
    subcategory: "PMP Series",
    brand: "Power-One",
    series: "PMP Series",
    model: "PMP 15",
    capacity: "15 kVA / 12 kW",
    price: 0,
    rating: 4.9,
    stock: 10,
    image: "/images/products/power-one/pmp_dropdown.png",
    images: [
      "/images/products/power-one/pmp_dropdown.png",
      "/images/products/power-one/product_pmp.svg",
    ],
    tagline: "Heavy-duty 15 kVA 3P:3P industrial online UPS with DSP control and galvanic isolation.",
    description: "The Power-One PMP 15 delivers 12 kW of regulated, pure sine wave power for sensitive commercial, medical, and manufacturing loads. Built with dual conversion technology, robust transient recovery within 1 cycle, and full isolation transformer protection.",
    warranty: "2 Years Manufacturer Warranty",
    badges: ["Power-One Official", "3Ph In / 3Ph Out", "Galvanic Isolation", "Quote on Request"],
    specs: [
      { label: "Series", value: "PMP Series" },
      { label: "Model", value: "PMP 15" },
      { label: "Capacity Rating", value: "15 kVA / 12 kW" },
      { label: "Phase Configuration", value: "3 Phase In / 3 Phase Out (3Ph+N)" },
      { label: "Input Voltage", value: "400VAC / 415VAC (305VAC ~ 485VAC Range)" },
      { label: "Input Frequency", value: "40 Hz to 70 Hz" },
      { label: "Output Voltage", value: "380VAC / 400VAC / 415VAC (±1% Regulation)" },
      { label: "DC Bus / Battery Voltage", value: "384 VDC (12V x 32 Nos)" },
      { label: "Dimensions (W x D x H)", value: "405 x 656 x 817 mm" },
      { label: "Net Weight", value: "120 kg" },
    ],
    features: [
      "True double conversion online design with built-in galvanic isolation transformer",
      "Advanced battery management with adjustable charging current up to 40A",
      "Dynamic regulation ±5% for 10% to 90% step load with 1-cycle recovery",
      "Static bypass transfer time: 0 ms",
      "Complies with IEC/EN 62040-1, 62040-2, 62040-3 safety and performance standards",
    ],
    applications: [
      "Diagnostic Clinics & Lab Equipment",
      "Mid-sized Server Rooms & Networking Closets",
      "Industrial Robotic Workstations",
      "Broadcasting Facilities",
    ],
    sourceUrl: "https://www.poweroneups.com/product/pmp-series",
  },
  {
    id: "power-one-pmp-20kva",
    name: "Power-One PMP 20kVA / 16kW 3-Phase Online UPS",
    category: "Power-One UPS",
    subcategory: "PMP Series",
    brand: "Power-One",
    series: "PMP Series",
    model: "PMP 20",
    capacity: "20 kVA / 16 kW",
    price: 0,
    rating: 4.9,
    stock: 8,
    image: "/images/products/power-one/pmp_dropdown.png",
    images: [
      "/images/products/power-one/pmp_dropdown.png",
      "/images/products/power-one/product_pmp.svg",
    ],
    tagline: "Industrial 20 kVA 3-phase true double conversion UPS for healthcare and manufacturing.",
    description: "Engineered for 24/7 continuous operation, the Power-One PMP 20 kVA UPS features an ultra-rugged inverter bridge, 384 VDC battery architecture, and comprehensive multi-layer hardware protections against power surges, phase shifts, and voltage sags.",
    warranty: "2 Years Manufacturer Warranty",
    badges: ["Power-One Official", "3Ph In / 3Ph Out", "Enterprise Grade", "Quote on Request"],
    specs: [
      { label: "Series", value: "PMP Series" },
      { label: "Model", value: "PMP 20" },
      { label: "Capacity Rating", value: "20 kVA / 16 kW" },
      { label: "Phase Configuration", value: "3 Phase In / 3 Phase Out" },
      { label: "Input Voltage", value: "400VAC / 415VAC (305V ~ 485V Ph-Ph)" },
      { label: "Output Voltage", value: "380VAC / 400VAC / 415VAC (±1%)" },
      { label: "Battery Voltage", value: "384 VDC (348V-384V adjustable)" },
      { label: "Dimensions (W x D x H)", value: "405 x 656 x 817 mm" },
      { label: "Net Weight", value: "145 kg" },
    ],
    features: [
      "Galvanic isolation transformer provides total load-to-grid noise separation",
      "Full digital DSP microprocessor control",
      "Intelligent battery charger with default 10A and maximum 40A rate",
      "Parallel capability for redundancy (N+1) or capacity expansion",
    ],
    applications: ["Hospitals", "Corporate Data Centers", "Pharmaceutical Manufacturing", "Printing Presses"],
    sourceUrl: "https://www.poweroneups.com/product/pmp-series",
  },
  {
    id: "power-one-pmp-30kva",
    name: "Power-One PMP 30kVA / 24kW 3-Phase Online UPS",
    category: "Power-One UPS",
    subcategory: "PMP Series",
    brand: "Power-One",
    series: "PMP Series",
    model: "PMP 30",
    capacity: "30 kVA / 24 kW",
    price: 0,
    rating: 4.9,
    stock: 6,
    image: "/images/products/power-one/pmp_dropdown.png",
    images: [
      "/images/products/power-one/pmp_dropdown.png",
      "/images/products/power-one/product_pmp.svg",
    ],
    tagline: "High-performance 30 kVA 3P:3P UPS with full isolation transformer protection.",
    description: "The Power-One PMP 30 provides 24 kW of clean, continuous sine wave electricity. Built with high thermal endurance, rugged sheet-metal enclosure, and modular internal sub-assemblies for rapid servicing.",
    warranty: "2 Years Manufacturer Warranty",
    badges: ["Power-One Official", "3Ph In / 3Ph Out", "Industrial UPS", "Quote on Request"],
    specs: [
      { label: "Series", value: "PMP Series" },
      { label: "Model", value: "PMP 30" },
      { label: "Capacity Rating", value: "30 kVA / 24 kW" },
      { label: "Phase Configuration", value: "3 Phase In / 3 Phase Out" },
      { label: "Input Voltage", value: "400VAC / 415VAC (305V ~ 485V Range)" },
      { label: "Output Voltage", value: "380VAC / 400VAC / 415VAC (±1%)" },
      { label: "Dimensions (W x D x H)", value: "405 x 656 x 941 mm" },
      { label: "Net Weight", value: "193 kg" },
    ],
    features: [
      "True double conversion technology with full galvanic isolation",
      "Zero transfer time static switch and manual maintenance bypass",
      "Crest factor 3:1 handles severe non-linear IT and industrial loads",
    ],
    applications: ["Banking Data Hubs", "Industrial Automation", "Medical Scanners", "Process Plants"],
    sourceUrl: "https://www.poweroneups.com/product/pmp-series",
  },
  {
    id: "power-one-pmp-40kva",
    name: "Power-One PMP 40kVA / 32kW 3-Phase Online UPS",
    category: "Power-One UPS",
    subcategory: "PMP Series",
    brand: "Power-One",
    series: "PMP Series",
    model: "PMP 40",
    capacity: "40 kVA / 32 kW",
    price: 0,
    rating: 5.0,
    stock: 5,
    image: "/images/products/power-one/pmp_dropdown.png",
    images: [
      "/images/products/power-one/pmp_dropdown.png",
      "/images/products/power-one/product_pmp.svg",
    ],
    tagline: "Industrial 40 kVA 3-phase enterprise power continuity system.",
    description: "The Power-One PMP 40 kVA UPS provides 32 kW capacity with an advanced DSP architecture, 384 VDC battery bank support, and heavy-duty magnetic components engineered to withstand severe power anomalies.",
    warranty: "2 Years Manufacturer Warranty",
    badges: ["Power-One Official", "3Ph In / 3Ph Out", "Continuous Duty", "Quote on Request"],
    specs: [
      { label: "Series", value: "PMP Series" },
      { label: "Model", value: "PMP 40" },
      { label: "Capacity Rating", value: "40 kVA / 32 kW" },
      { label: "Phase Configuration", value: "3 Phase In / 3 Phase Out" },
      { label: "Dimensions (W x D x H)", value: "432 x 821 x 1159 mm" },
      { label: "Net Weight", value: "275 kg" },
    ],
    features: [
      "Industrial inverter design with heavy-duty output isolation transformer",
      "Cold start on battery capability",
      "Advanced mimic LCD panel with complete telemetry and fault diagnostics",
    ],
    applications: ["Industrial Manufacturing", "Airports & Rail Infrastructure", "Central Server Farms"],
    sourceUrl: "https://www.poweroneups.com/product/pmp-series",
  },
  {
    id: "power-one-pmp-60kva",
    name: "Power-One PMP 60kVA / 48kW 3-Phase Online UPS",
    category: "Power-One UPS",
    subcategory: "PMP Series",
    brand: "Power-One",
    series: "PMP Series",
    model: "PMP 60",
    capacity: "60 kVA / 48 kW",
    price: 0,
    rating: 5.0,
    stock: 4,
    image: "/images/products/power-one/pmp_dropdown.png",
    images: [
      "/images/products/power-one/pmp_dropdown.png",
      "/images/products/power-one/product_pmp.svg",
    ],
    tagline: "Enterprise 60 kVA 3-phase double conversion UPS for critical facilities.",
    description: "The Power-One PMP 60 kVA provides 48 kW true active power output. Features dual independent DSP controllers for rectifier and inverter, heavy-duty copper-wound isolation transformer, and robust fault-clearing capabilities.",
    warranty: "2 Years Manufacturer Warranty",
    badges: ["Power-One Official", "3Ph In / 3Ph Out", "Mission Critical", "Quote on Request"],
    specs: [
      { label: "Series", value: "PMP Series" },
      { label: "Model", value: "PMP 60" },
      { label: "Capacity Rating", value: "60 kVA / 48 kW" },
      { label: "Phase Configuration", value: "3 Phase In / 3 Phase Out" },
      { label: "Dimensions (W x D x H)", value: "432 x 821 x 1159 mm" },
      { label: "Net Weight", value: "365 kg" },
    ],
    features: [
      "Dual DSP controller architecture for superior response and regulation",
      "Galvanic isolation transformer as standard",
      "Intelligent battery management extending battery life by up to 50%",
    ],
    applications: ["Heavy Industrial Processing", "Major Hospitals", "Telecommunication NOCs"],
    sourceUrl: "https://www.poweroneups.com/product/pmp-series",
  },
  {
    id: "power-one-pmp-80kva",
    name: "Power-One PMP 80kVA / 64kW 3-Phase Online UPS",
    category: "Power-One UPS",
    subcategory: "PMP Series",
    brand: "Power-One",
    series: "PMP Series",
    model: "PMP 80",
    capacity: "80 kVA / 64 kW",
    price: 0,
    rating: 5.0,
    stock: 3,
    image: "/images/products/power-one/pmp_dropdown.png",
    images: [
      "/images/products/power-one/pmp_dropdown.png",
      "/images/products/power-one/product_pmp.svg",
    ],
    tagline: "High-capacity 80 kVA industrial 3-phase online UPS with isolation transformer.",
    description: "The Power-One PMP 80 kVA UPS system delivers 64 kW of rock-solid power to large-scale infrastructure. Equipped with rugged IGBT technology, static bypass, and comprehensive environmental monitoring.",
    warranty: "2 Years Manufacturer Warranty",
    badges: ["Power-One Official", "3Ph In / 3Ph Out", "Industrial Grade", "Quote on Request"],
    specs: [
      { label: "Series", value: "PMP Series" },
      { label: "Model", value: "PMP 80" },
      { label: "Capacity Rating", value: "80 kVA / 64 kW" },
      { label: "Phase Configuration", value: "3 Phase In / 3 Phase Out" },
      { label: "Dimensions (W x D x H)", value: "554 x 975 x 1286 mm" },
      { label: "Net Weight", value: "471 kg" },
    ],
    features: [
      "Industrial sheet steel enclosure with IP21 protection",
      "Full galvanic isolation protecting downstream loads from common mode surges",
      "Advanced event logging up to 1,200 events recorded in non-volatile memory",
    ],
    applications: ["Semiconductor / Cleanroom Plants", "Large Hospital Campuses", "Critical Infrastructure"],
    sourceUrl: "https://www.poweroneups.com/product/pmp-series",
  },
  {
    id: "power-one-pmp-100kva",
    name: "Power-One PMP 100kVA / 80kW 3-Phase Online UPS",
    category: "Power-One UPS",
    subcategory: "PMP Series",
    brand: "Power-One",
    series: "PMP Series",
    model: "PMP 100",
    capacity: "100 kVA / 80 kW",
    price: 0,
    rating: 5.0,
    stock: 3,
    image: "/images/products/power-one/pmp_dropdown.png",
    images: [
      "/images/products/power-one/pmp_dropdown.png",
      "/images/products/power-one/product_pmp.svg",
    ],
    tagline: "Enterprise 100 kVA 3-phase online double conversion power protection system.",
    description: "The Power-One PMP 100 is engineered for massive commercial and industrial infrastructure requiring 80 kW of continuous conditioned power. Built with heavy-duty magnetics and advanced cooling channels.",
    warranty: "2 Years Manufacturer Warranty",
    badges: ["Power-One Official", "3Ph In / 3Ph Out", "Enterprise Scale", "Quote on Request"],
    specs: [
      { label: "Series", value: "PMP Series" },
      { label: "Model", value: "PMP 100" },
      { label: "Capacity Rating", value: "100 kVA / 80 kW" },
      { label: "Phase Configuration", value: "3 Phase In / 3 Phase Out" },
      { label: "Dimensions (W x D x H)", value: "635 x 976 x 1326 mm" },
      { label: "Net Weight", value: "573 kg" },
    ],
    features: [
      "High efficiency up to 94% in double conversion mode and 98% in ECO mode",
      "Built-in isolation transformer for maximum safety and noise attenuation",
      "Parallelable up to 8 units for N+1 redundancy or multi-megawatt configurations",
    ],
    applications: ["Tier 3 / Tier 4 Data Centers", "Textile & Steel Mills", "Central Financial Clearing Desks"],
    sourceUrl: "https://www.poweroneups.com/product/pmp-series",
  },
  {
    id: "power-one-pmp-120kva",
    name: "Power-One PMP 120kVA / 96kW 3-Phase Online UPS",
    category: "Power-One UPS",
    subcategory: "PMP Series",
    brand: "Power-One",
    series: "PMP Series",
    model: "PMP 120",
    capacity: "120 kVA / 96 kW",
    price: 0,
    rating: 5.0,
    stock: 2,
    image: "/images/products/power-one/pmp_dropdown.png",
    images: [
      "/images/products/power-one/pmp_dropdown.png",
      "/images/products/power-one/product_pmp.svg",
    ],
    tagline: "Industrial 120 kVA 3P:3P double conversion UPS with galvanic isolation.",
    description: "The Power-One PMP 120 kVA UPS system provides 96 kW of high-density clean power. Features integrated static bypass, heavy-duty copper magnetic core, and advanced battery charging algorithms.",
    warranty: "2 Years Manufacturer Warranty",
    badges: ["Power-One Official", "3Ph In / 3Ph Out", "Industrial Scale", "Quote on Request"],
    specs: [
      { label: "Series", value: "PMP Series" },
      { label: "Model", value: "PMP 120" },
      { label: "Capacity Rating", value: "120 kVA / 96 kW" },
      { label: "Phase Configuration", value: "3 Phase In / 3 Phase Out" },
      { label: "Net Weight", value: "650 kg" },
    ],
    features: [
      "Rugged industrial construction designed for high-ambient temperature environments",
      "Galvanic isolation transformer standard on output",
      "Comprehensive telemetry: RS485 MODBUS, SNMP, Dry Contacts",
    ],
    applications: ["Heavy Process Automation", "Commercial Malls", "National Telecom Hubs"],
    sourceUrl: "https://www.poweroneups.com/product/pmp-series",
  },
  {
    id: "power-one-pmp-160kva",
    name: "Power-One PMP 160kVA / 128kW 3-Phase Online UPS",
    category: "Power-One UPS",
    subcategory: "PMP Series",
    brand: "Power-One",
    series: "PMP Series",
    model: "PMP 160",
    capacity: "160 kVA / 128 kW",
    price: 0,
    rating: 5.0,
    stock: 2,
    image: "/images/products/power-one/pmp_dropdown.png",
    images: [
      "/images/products/power-one/pmp_dropdown.png",
      "/images/products/power-one/product_pmp.svg",
    ],
    tagline: "Heavy-duty 160 kVA 3-phase online UPS for large industrial facilities.",
    description: "The Power-One PMP 160 delivers 128 kW of robust, uncompromised power backup for mission-critical operations. Designed with galvanic isolation, high short-circuit withstand, and intelligent multi-mode battery charging.",
    warranty: "2 Years Manufacturer Warranty",
    badges: ["Power-One Official", "3Ph In / 3Ph Out", "Industrial Grade", "Quote on Request"],
    specs: [
      { label: "Series", value: "PMP Series" },
      { label: "Model", value: "PMP 160" },
      { label: "Capacity Rating", value: "160 kVA / 128 kW" },
      { label: "Phase Configuration", value: "3 Phase In / 3 Phase Out" },
      { label: "Net Weight", value: "760 kg" },
    ],
    features: [
      "Ultra-low THD (<1% linear, <3% non-linear)",
      "High crest factor handling 3:1",
      "Full digital DSP architecture with comprehensive diagnostics",
    ],
    applications: ["Heavy Industrial Infrastructure", "Regional Data Centers", "Hospitals"],
    sourceUrl: "https://www.poweroneups.com/product/pmp-series",
  },
  {
    id: "power-one-pmp-200kva",
    name: "Power-One PMP 200kVA / 160kW 3-Phase Online UPS",
    category: "Power-One UPS",
    subcategory: "PMP Series",
    brand: "Power-One",
    series: "PMP Series",
    model: "PMP 200",
    capacity: "200 kVA / 160 kW",
    price: 0,
    rating: 5.0,
    stock: 2,
    image: "/images/products/power-one/pmp_dropdown.png",
    images: [
      "/images/products/power-one/pmp_dropdown.png",
      "/images/products/power-one/product_pmp.svg",
    ],
    tagline: "Utility-scale 200 kVA 3-phase online UPS with galvanic isolation transformer.",
    description: "The Power-One PMP 200 kVA system delivers 160 kW of continuous high-reliability power. Built in a robust standalone enclosure measuring 705 x 1051 x 1646 mm with a net weight of 845 kg.",
    warranty: "2 Years Manufacturer Warranty",
    badges: ["Power-One Official", "3Ph In / 3Ph Out", "Megawatt Ready", "Quote on Request"],
    specs: [
      { label: "Series", value: "PMP Series" },
      { label: "Model", value: "PMP 200" },
      { label: "Capacity Rating", value: "200 kVA / 160 kW" },
      { label: "Phase Configuration", value: "3 Phase In / 3 Phase Out" },
      { label: "Dimensions (W x D x H)", value: "705 x 1051 x 1646 mm" },
      { label: "Net Weight", value: "845 kg" },
    ],
    features: [
      "Heavy-duty industrial inverter with output isolation transformer",
      "Parallel architecture up to 8 units for total 1.6 MVA capacity",
      "Dynamic regulation ±5% with 1-cycle transient recovery",
    ],
    applications: ["Large Manufacturing Plants", "Campus Data Centers", "Critical Utility Infrastructure"],
    sourceUrl: "https://www.poweroneups.com/product/pmp-series",
  },
  {
    id: "power-one-pmp-300kva",
    name: "Power-One PMP 300kVA / 240kW 3-Phase Online UPS",
    category: "Power-One UPS",
    subcategory: "PMP Series",
    brand: "Power-One",
    series: "PMP Series",
    model: "PMP 300",
    capacity: "300 kVA / 240 kW",
    price: 0,
    rating: 5.0,
    stock: 1,
    image: "/images/products/power-one/pmp_dropdown.png",
    images: [
      "/images/products/power-one/pmp_dropdown.png",
      "/images/products/power-one/product_pmp.svg",
    ],
    tagline: "Utility-grade 300 kVA 3-phase industrial UPS with copper isolation transformer.",
    description: "Delivering 240 kW of clean, uninterruptible power, the Power-One PMP 300 is built for hyperscale facilities and heavy manufacturing. Dimensions: 1000 x 1400 x 1900 mm, weight: 1,690 kg.",
    warranty: "2 Years Manufacturer Warranty",
    badges: ["Power-One Official", "3Ph In / 3Ph Out", "Heavy Industrial", "Quote on Request"],
    specs: [
      { label: "Series", value: "PMP Series" },
      { label: "Model", value: "PMP 300" },
      { label: "Capacity Rating", value: "300 kVA / 240 kW" },
      { label: "Phase Configuration", value: "3 Phase In / 3 Phase Out" },
      { label: "Dimensions (W x D x H)", value: "1000 x 1400 x 1900 mm" },
      { label: "Net Weight", value: "1690 kg" },
    ],
    features: [
      "Highest industrial grade construction with galvanic isolation",
      "Advanced dual DSP controller architecture",
      "Seamless integration with diesel generator sets and solar hybrid systems",
    ],
    applications: ["Industrial Metallurgy", "National Healthcare Hubs", "Colocation Data Centers"],
    sourceUrl: "https://www.poweroneups.com/product/pmp-series",
  },
  {
    id: "power-one-pmp-400kva",
    name: "Power-One PMP 400kVA / 320kW 3-Phase Online UPS",
    category: "Power-One UPS",
    subcategory: "PMP Series",
    brand: "Power-One",
    series: "PMP Series",
    model: "PMP 400",
    capacity: "400 kVA / 320 kW",
    price: 0,
    rating: 5.0,
    stock: 1,
    image: "/images/products/power-one/pmp_dropdown.png",
    images: [
      "/images/products/power-one/pmp_dropdown.png",
      "/images/products/power-one/product_pmp.svg",
    ],
    tagline: "Industrial 400 kVA 3P:3P online double conversion system for critical infrastructure.",
    description: "The Power-One PMP 400 kVA system provides 320 kW of continuous conditioned power. Engineered with a massive copper isolation transformer, full digital telemetry, and dual static bypass. Dimensions: 1000 x 1640 x 1900 mm, weight: 2,665 kg.",
    warranty: "2 Years Manufacturer Warranty",
    badges: ["Power-One Official", "3Ph In / 3Ph Out", "Heavy Duty", "Quote on Request"],
    specs: [
      { label: "Series", value: "PMP Series" },
      { label: "Model", value: "PMP 400" },
      { label: "Capacity Rating", value: "400 kVA / 320 kW" },
      { label: "Phase Configuration", value: "3 Phase In / 3 Phase Out" },
      { label: "Dimensions (W x D x H)", value: "1000 x 1640 x 1900 mm" },
      { label: "Net Weight", value: "2665 kg" },
    ],
    features: [
      "Robust fault-clearing capabilities and superior transient recovery",
      "Galvanic isolation transformer standard on output",
      "Full network management: RS232, RS485 MODBUS, SNMP, DRY contacts",
    ],
    applications: ["Hyperscale Cloud Data Centers", "Large Airport Facilities", "Petrochemical Refineries"],
    sourceUrl: "https://www.poweroneups.com/product/pmp-series",
  },
  {
    id: "power-one-pmp-500kva",
    name: "Power-One PMP 500kVA / 400kW 3-Phase Online UPS",
    category: "Power-One UPS",
    subcategory: "PMP Series",
    brand: "Power-One",
    series: "PMP Series",
    model: "PMP 500",
    capacity: "500 kVA / 400 kW",
    price: 0,
    rating: 5.0,
    stock: 1,
    image: "/images/products/power-one/pmp_dropdown.png",
    images: [
      "/images/products/power-one/pmp_dropdown.png",
      "/images/products/power-one/product_pmp.svg",
    ],
    tagline: "Flagship 500 kVA 3-phase industrial double conversion online UPS.",
    description: "The flagship of the Power-One PMP line, the PMP 500 kVA delivers 400 kW of continuous, ultra-clean power to national-scale critical loads. Built in an expansive cabinet (1000 x 2580 x 1900 mm, weight: 3,730 kg) with full galvanic isolation, parallel architecture up to 8 units (4 MVA total), and advanced thermal management.",
    warranty: "2 Years Manufacturer Warranty",
    badges: ["Power-One Official", "3Ph In / 3Ph Out", "Flagship Industrial", "Quote on Request"],
    specs: [
      { label: "Series", value: "PMP Series" },
      { label: "Model", value: "PMP 500" },
      { label: "Capacity Rating", value: "500 kVA / 400 kW" },
      { label: "Phase Configuration", value: "3 Phase In / 3 Phase Out" },
      { label: "Dimensions (W x D x H)", value: "1000 x 2580 x 1900 mm" },
      { label: "Net Weight", value: "3730 kg" },
    ],
    features: [
      "Maximum continuous capacity 500 kVA / 400 kW with 3:1 crest factor",
      "Output galvanic isolation transformer for absolute electrical safety",
      "Paralleling capability up to 8 units for total 4,000 kVA system rating",
      "Meets ISO 9001, ISO 14001, ISO 45001, ISO 50001, IEC 62040-1/2/3 standards",
    ],
    applications: ["Mega Data Centers", "National Grid Substations", "Major Industrial Complexes", "International Airports"],
    sourceUrl: "https://www.poweroneups.com/product/pmp-series",
  },

  /* ══════════════════════════════════════════════════════════════════
     2. POWER-ONE UPS — PTM SERIES (Single Phase Output Series)
     - 6 kVA (1P In / 1P Out)
     - 11 kVA to 40 kVA (3P In / 1P Out)
     Reference: https://www.poweroneups.com/product/ptm-series
     ══════════════════════════════════════════════════════════════════ */
  {
    id: "power-one-ptm-6kva",
    name: "Power-One PTM 6kVA Single Phase Online UPS (1P:1P)",
    category: "Power-One UPS",
    subcategory: "PTM Series",
    brand: "Power-One",
    series: "PTM Series",
    model: "PTM 6",
    capacity: "6 kVA / 4.8 kW",
    price: 0,
    rating: 4.8,
    stock: 15,
    image: "/images/products/power-one/ptm_dropdown.png",
    images: [
      "/images/products/power-one/ptm_dropdown.png",
      "/images/products/power-one/ptm1.png",
      "/images/products/power-one/ptm2.png",
      "/images/products/power-one/ptm3.png",
    ],
    tagline: "Single phase 6 kVA online UPS with 1-Phase input and 1-Phase output.",
    description: "The Power-One PTM 6 kVA is a dedicated single-phase double-conversion online UPS system (1P Input / 1P Output) featuring an integrated isolation transformer, DSP digital control, and zero transfer time. Ideal for commercial offices, sensitive lab instruments, and diagnostic equipment.",
    warranty: "2 Years Manufacturer Warranty",
    badges: ["Power-One Official", "1Ph In / 1Ph Out", "PTM Series", "Quote on Request"],
    specs: [
      { label: "Series", value: "PTM Series" },
      { label: "Model", value: "PTM 6" },
      { label: "Capacity Rating", value: "6 kVA / 4.8 kW" },
      { label: "Phase Configuration", value: "1 Phase In / 1 Phase Out (1P:1P)" },
      { label: "Input Voltage", value: "230VAC (140V ~ 290V Range)" },
      { label: "Output Voltage", value: "230VAC ±1% Pure Sine Wave" },
      { label: "Transfer Time", value: "Zero (0 ms)" },
      { label: "Battery Bank Voltage", value: "192 VDC / 240 VDC" },
    ],
    features: [
      "True online double conversion technology with galvanic isolation transformer",
      "Dedicated 1 Phase Input and 1 Phase Output configuration",
      "Wide input voltage tolerance protecting against brownouts and high voltage spikes",
      "Cold start capability and intelligent battery charging",
    ],
    applications: ["Medical Ultrasound & Pathology Equipment", "Office Server Racks", "Security & Surveillance Hubs"],
    sourceUrl: "https://www.poweroneups.com/product/ptm-series",
  },
  {
    id: "power-one-ptm-11kva",
    name: "Power-One PTM 11kVA 3-Phase In / 1-Phase Out Online UPS",
    category: "Power-One UPS",
    subcategory: "PTM Series",
    brand: "Power-One",
    series: "PTM Series",
    model: "PTM 11",
    capacity: "11 kVA / 8.8 kW",
    price: 0,
    rating: 4.9,
    stock: 10,
    image: "/images/products/power-one/ptm_dropdown.png",
    images: [
      "/images/products/power-one/ptm_dropdown.png",
      "/images/products/power-one/ptm1.png",
      "/images/products/power-one/ptm2.png",
      "/images/products/power-one/ptm3.png",
    ],
    tagline: "Industrial 11 kVA UPS with 3-Phase input and high-power 1-Phase output (3P:1P).",
    description: "The Power-One PTM 11 features a 3-phase utility input to balance loads across all incoming mains phases while delivering a heavy single-phase 230V output. Perfect for buildings with 3-phase grid supplies feeding large single-phase critical loads.",
    warranty: "2 Years Manufacturer Warranty",
    badges: ["Power-One Official", "3Ph In / 1Ph Out", "Phase Balancing", "Quote on Request"],
    specs: [
      { label: "Series", value: "PTM Series" },
      { label: "Model", value: "PTM 11" },
      { label: "Capacity Rating", value: "11 kVA / 8.8 kW" },
      { label: "Phase Configuration", value: "3 Phase In / 1 Phase Out (3P:1P)" },
      { label: "Input Voltage", value: "400VAC / 415VAC (305V ~ 485V Ph-Ph)" },
      { label: "Output Voltage", value: "230VAC ±1% Single Phase" },
      { label: "Battery Bank", value: "384 VDC nominal" },
    ],
    features: [
      "Balances phase current across 3-phase supply while delivering pure single-phase power",
      "Built-in copper galvanic isolation transformer on output",
      "Zero transfer time static bypass with automatic fault transfer",
    ],
    applications: ["Printing Machinery", "Commercial Elevators", "Broadcast Transmitters", "Hospital Wards"],
    sourceUrl: "https://www.poweroneups.com/product/ptm-series",
  },
  {
    id: "power-one-ptm-15kva",
    name: "Power-One PTM 15kVA 3-Phase In / 1-Phase Out Online UPS",
    category: "Power-One UPS",
    subcategory: "PTM Series",
    brand: "Power-One",
    series: "PTM Series",
    model: "PTM 15",
    capacity: "15 kVA / 12 kW",
    price: 0,
    rating: 4.9,
    stock: 8,
    image: "/images/products/power-one/ptm_dropdown.png",
    images: [
      "/images/products/power-one/ptm_dropdown.png",
      "/images/products/power-one/ptm1.png",
      "/images/products/power-one/ptm2.png",
    ],
    tagline: "Industrial 15 kVA (3P:1P) online double conversion UPS with galvanic isolation.",
    description: "The Power-One PTM 15 provides 12 kW of single-phase power fed from a three-phase mains source. Designed for facilities that require substantial single-phase power without overloading an individual mains phase.",
    warranty: "2 Years Manufacturer Warranty",
    badges: ["Power-One Official", "3Ph In / 1Ph Out", "Isolation Transformer", "Quote on Request"],
    specs: [
      { label: "Series", value: "PTM Series" },
      { label: "Model", value: "PTM 15" },
      { label: "Capacity Rating", value: "15 kVA / 12 kW" },
      { label: "Phase Configuration", value: "3 Phase In / 1 Phase Out (3P:1P)" },
      { label: "Input Voltage", value: "400VAC / 415VAC (3Ph+N)" },
      { label: "Output Voltage", value: "230VAC ±1% (1Ph+N)" },
    ],
    features: [
      "3-phase input draws balanced currents from utility grid",
      "Pure sine wave output with total harmonic distortion < 1%",
      "Maintenance bypass switch allows servicing without dropping the load",
    ],
    applications: ["Industrial Control Systems", "Telecom Stations", "Educational Campuses"],
    sourceUrl: "https://www.poweroneups.com/product/ptm-series",
  },
  {
    id: "power-one-ptm-20kva",
    name: "Power-One PTM 20kVA 3-Phase In / 1-Phase Out Online UPS",
    category: "Power-One UPS",
    subcategory: "PTM Series",
    brand: "Power-One",
    series: "PTM Series",
    model: "PTM 20",
    capacity: "20 kVA / 16 kW",
    price: 0,
    rating: 4.9,
    stock: 6,
    image: "/images/products/power-one/ptm_dropdown.png",
    images: [
      "/images/products/power-one/ptm_dropdown.png",
      "/images/products/power-one/ptm1.png",
      "/images/products/power-one/ptm2.png",
    ],
    tagline: "High-capacity 20 kVA (3P:1P) online UPS for heavy single-phase industrial loads.",
    description: "The Power-One PTM 20 delivers 16 kW single-phase output with a 3-phase input interface. Features advanced DSP processing, robust galvanic isolation, and high crest factor current support.",
    warranty: "2 Years Manufacturer Warranty",
    badges: ["Power-One Official", "3Ph In / 1Ph Out", "Industrial UPS", "Quote on Request"],
    specs: [
      { label: "Series", value: "PTM Series" },
      { label: "Model", value: "PTM 20" },
      { label: "Capacity Rating", value: "20 kVA / 16 kW" },
      { label: "Phase Configuration", value: "3 Phase In / 1 Phase Out (3P:1P)" },
      { label: "Output Voltage", value: "230VAC ±1%" },
      { label: "Crest Factor", value: "3:1" },
    ],
    features: [
      "True double conversion with integrated copper galvanic isolation transformer",
      "Wide input operating range from 305V to 485V AC",
      "Comprehensive telemetry: RS232, RS485 MODBUS, SNMP",
    ],
    applications: ["Diagnostic Scanning Suites", "Commercial Textile Units", "High-Rise Building Automation"],
    sourceUrl: "https://www.poweroneups.com/product/ptm-series",
  },
  {
    id: "power-one-ptm-30kva",
    name: "Power-One PTM 30kVA 3-Phase In / 1-Phase Out Online UPS",
    category: "Power-One UPS",
    subcategory: "PTM Series",
    brand: "Power-One",
    series: "PTM Series",
    model: "PTM 30",
    capacity: "30 kVA / 24 kW",
    price: 0,
    rating: 5.0,
    stock: 4,
    image: "/images/products/power-one/ptm_dropdown.png",
    images: [
      "/images/products/power-one/ptm_dropdown.png",
      "/images/products/power-one/ptm1.png",
      "/images/products/power-one/ptm2.png",
    ],
    tagline: "Heavy-duty 30 kVA (3P:1P) online UPS for large single-phase enterprise setups.",
    description: "The Power-One PTM 30 supplies 24 kW of clean single-phase power from a 3-phase power supply. Designed with high overload handling, robust fault protection, and a heavy-duty isolation transformer.",
    warranty: "2 Years Manufacturer Warranty",
    badges: ["Power-One Official", "3Ph In / 1Ph Out", "High Power 1P", "Quote on Request"],
    specs: [
      { label: "Series", value: "PTM Series" },
      { label: "Model", value: "PTM 30" },
      { label: "Capacity Rating", value: "30 kVA / 24 kW" },
      { label: "Phase Configuration", value: "3 Phase In / 1 Phase Out (3P:1P)" },
      { label: "Output Voltage", value: "230VAC ±1%" },
    ],
    features: [
      "3-phase input load balancing with heavy 1-phase output delivery",
      "Full galvanic isolation eliminates common-mode electrical noise",
      "Zero transfer time static bypass switch",
    ],
    applications: ["Large Medical Facilities", "Heavy Printing Machinery", "Broadcast Studios"],
    sourceUrl: "https://www.poweroneups.com/product/ptm-series",
  },
  {
    id: "power-one-ptm-40kva",
    name: "Power-One PTM 40kVA 3-Phase In / 1-Phase Out Online UPS",
    category: "Power-One UPS",
    subcategory: "PTM Series",
    brand: "Power-One",
    series: "PTM Series",
    model: "PTM 40",
    capacity: "40 kVA / 32 kW",
    price: 0,
    rating: 5.0,
    stock: 3,
    image: "/images/products/power-one/ptm_dropdown.png",
    images: [
      "/images/products/power-one/ptm_dropdown.png",
      "/images/products/power-one/ptm1.png",
      "/images/products/power-one/ptm2.png",
    ],
    tagline: "Maximum capacity 40 kVA 3P:1P online UPS for industrial single-phase applications.",
    description: "The Power-One PTM 40 represents the largest standard rating in the PTM line, providing 32 kW of single-phase power while maintaining 3-phase load balance across incoming mains. Built with heavy-duty magnetics and advanced cooling.",
    warranty: "2 Years Manufacturer Warranty",
    badges: ["Power-One Official", "3Ph In / 1Ph Out", "Top PTM Model", "Quote on Request"],
    specs: [
      { label: "Series", value: "PTM Series" },
      { label: "Model", value: "PTM 40" },
      { label: "Capacity Rating", value: "40 kVA / 32 kW" },
      { label: "Phase Configuration", value: "3 Phase In / 1 Phase Out (3P:1P)" },
      { label: "Output Voltage", value: "230VAC ±1% Single Phase" },
    ],
    features: [
      "Maximum single-phase output capacity of 32 kW with 3-phase input connection",
      "Built-in heavy copper isolation transformer",
      "Dual DSP controller architecture with digital mimic panel",
    ],
    applications: ["Industrial Automation", "Medical Research Centers", "Commercial Complexes"],
    sourceUrl: "https://www.poweroneups.com/product/ptm-series",
  },

  /* ══════════════════════════════════════════════════════════════════
     3. POWER-ONE SOLAR — ON-GRID / GRID-TIE INVERTERS
     - Single Phase: 1kW, 2kW, 3kW, 5kW, 6kW (SGTU Series)
     - Three Phase: 5kW to 250kW Range
     Reference: https://poweroneups.com/product/solar-gridtie-invertor
     ══════════════════════════════════════════════════════════════════ */
  {
    id: "power-one-solar-ongrid-1kw",
    name: "Power-One SGTU-101-N 1kW Single Phase On-Grid Solar Inverter",
    category: "Power-One Solar",
    subcategory: "On-Grid Inverters",
    brand: "Power-One",
    series: "SGTU Series",
    model: "SGTU-101-N",
    capacity: "1 kW",
    price: 0,
    rating: 4.8,
    stock: 20,
    image: "/images/products/power-one/on_grid_1.png",
    images: [
      "/images/products/power-one/on_grid_1.png",
      "/images/products/power-one/on_grid_2.png",
      "/images/products/power-one/on_grid_3.png",
      "/images/products/power-one/on_grid_dropdown.png",
    ],
    tagline: "Compact single phase grid-tie string inverter with high MPPT efficiency.",
    description: "The Power-One SGTU-101-N is a high-efficiency single-phase on-grid solar string inverter designed for residential rooftop net metering. Featuring ultra-wide MPPT operating range (70V–500V), IP65 industrial protection class, and >97.3% maximum efficiency.",
    warranty: "5 Years Manufacturer Warranty",
    badges: ["Power-One Official", "1 Phase On-Grid", "IP65 Waterproof", "Quote on Request"],
    specs: [
      { label: "Series", value: "SGTU Series (Grid-Tie)" },
      { label: "Model", value: "SGTU-101-N" },
      { label: "Rated Output Power", value: "1 kW" },
      { label: "Nominal Input DC Power", value: "1 kW" },
      { label: "Max DC Input Voltage", value: "500 V" },
      { label: "Startup DC Input Voltage", value: "80 V" },
      { label: "MPPT Operating Range", value: "70V - 500V" },
      { label: "Max DC Input Current", value: "13 A" },
      { label: "Number of MPPT / Strings", value: "1 MPPT / 1 String" },
      { label: "Rated AC Grid Voltage", value: "230 V (140V - 290V range)" },
      { label: "Rated Grid Frequency", value: "50 Hz (45 - 55 Hz)" },
      { label: "THD", value: "< 3%" },
      { label: "Max Efficiency", value: "97.3%" },
      { label: "Ingress Protection", value: "IP65" },
    ],
    features: [
      "Transformer-less compact design with lightweight casing",
      "High MPPT efficiency > 99% for maximum energy yield throughout the day",
      "IP65 outdoor weather-resistant casing for rooftop installation",
      "Integrated LCD display with optional GPRS / Wi-Fi remote monitoring kit",
      "Built-in anti-islanding protection and NEA net-metering synchronization",
    ],
    applications: ["Residential Rooftop Solar", "Small Commercial Establishments", "Net-Metered Home Systems"],
    sourceUrl: "https://poweroneups.com/product/solar-gridtie-invertor",
  },
  {
    id: "power-one-solar-ongrid-2kw",
    name: "Power-One SGTU-102-N 2kW Single Phase On-Grid Solar Inverter",
    category: "Power-One Solar",
    subcategory: "On-Grid Inverters",
    brand: "Power-One",
    series: "SGTU Series",
    model: "SGTU-102-N",
    capacity: "2 kW",
    price: 0,
    rating: 4.8,
    stock: 18,
    image: "/images/products/power-one/on_grid_2.png",
    images: [
      "/images/products/power-one/on_grid_2.png",
      "/images/products/power-one/on_grid_1.png",
      "/images/products/power-one/on_grid_dropdown.png",
    ],
    tagline: "2 kW single phase grid-tie solar inverter with IP65 outdoor casing.",
    description: "The Power-One SGTU-102-N provides 2 kW rated AC grid output from solar PV arrays. Built with 500V max DC input voltage, 70V–500V MPPT window, and 8.7A rated grid output current.",
    warranty: "5 Years Manufacturer Warranty",
    badges: ["Power-One Official", "1 Phase On-Grid", "High MPPT Yield", "Quote on Request"],
    specs: [
      { label: "Series", value: "SGTU Series (Grid-Tie)" },
      { label: "Model", value: "SGTU-102-N" },
      { label: "Rated Output Power", value: "2 kW" },
      { label: "Max DC Input Voltage", value: "500 V" },
      { label: "Startup Voltage", value: "80 V" },
      { label: "MPPT Range", value: "70V - 500V" },
      { label: "Rated AC Grid Voltage", value: "230 V (140V - 290V range)" },
      { label: "Rated AC Output Current", value: "8.7 A" },
      { label: "Max Efficiency", value: "97.3%" },
      { label: "Ingress Protection", value: "IP65" },
    ],
    features: [
      "Transformer-less topology with low acoustic noise (<25 dB)",
      "Wide MPPT tracking range starting as low as 70V",
      "Full protection suite: Overvoltage, islanding, short circuit, reverse polarity",
    ],
    applications: ["Residential Solar Installations", "Townhouses", "Retail Shops"],
    sourceUrl: "https://poweroneups.com/product/solar-gridtie-invertor",
  },
  {
    id: "power-one-solar-ongrid-3kw",
    name: "Power-One SGTU-103-SN 3kW Single Phase On-Grid Solar Inverter",
    category: "Power-One Solar",
    subcategory: "On-Grid Inverters",
    brand: "Power-One",
    series: "SGTU Series",
    model: "SGTU-103-SN",
    capacity: "3 kW",
    price: 0,
    rating: 4.9,
    stock: 25,
    image: "/images/products/power-one/on_grid_1.png",
    images: [
      "/images/products/power-one/on_grid_1.png",
      "/images/products/power-one/on_grid_3.png",
      "/images/products/power-one/on_grid_dropdown.png",
    ],
    tagline: "3 kW single phase rooftop grid-tie inverter for residential net metering.",
    description: "The Power-One SGTU-103-SN delivers 3 kW continuous grid feed-in with 13.1A rated AC output current. Ideal for suburban homes and offices in Kathmandu and regional cities participating in net metering.",
    warranty: "5 Years Manufacturer Warranty",
    badges: ["Power-One Official", "1 Phase On-Grid", "Popular Choice", "Quote on Request"],
    specs: [
      { label: "Series", value: "SGTU Series (Grid-Tie)" },
      { label: "Model", value: "SGTU-103-SN" },
      { label: "Rated Output Power", value: "3 kW" },
      { label: "Max DC Input Voltage", value: "500 V" },
      { label: "Startup Voltage", value: "80 V" },
      { label: "MPPT Range", value: "70V - 500V" },
      { label: "Rated AC Output Current", value: "13.1 A" },
      { label: "Max Efficiency", value: "97.3%" },
      { label: "THD", value: "< 3%" },
    ],
    features: [
      "High MPPT tracking efficiency > 99%",
      "Natural convection cooling without noisy fans",
      "Supports cloud monitoring via Wi-Fi/GPRS mobile app",
    ],
    applications: ["Suburban Homes", "Offices", "Clinics", "Gas Stations"],
    sourceUrl: "https://poweroneups.com/product/solar-gridtie-invertor",
  },
  {
    id: "power-one-solar-ongrid-5kw",
    name: "Power-One SGTU-105N 5kW Single Phase On-Grid Solar Inverter",
    category: "Power-One Solar",
    subcategory: "On-Grid Inverters",
    brand: "Power-One",
    series: "SGTU Series",
    model: "SGTU-105N",
    capacity: "5 kW",
    price: 0,
    rating: 4.9,
    stock: 20,
    image: "/images/products/power-one/on_grid_3.png",
    images: [
      "/images/products/power-one/on_grid_3.png",
      "/images/products/power-one/on_grid_4.png",
      "/images/products/power-one/on_grid_dropdown.png",
    ],
    tagline: "High-yield 5 kW single phase grid-tie inverter with dual MPPT strings.",
    description: "The Power-One SGTU-105N provides 5 kW AC grid power with 22A rated current. Features 100V–500V MPPT range, maximum efficiency of 97.5%, and robust IP65 weatherproofing.",
    warranty: "5 Years Manufacturer Warranty",
    badges: ["Power-One Official", "1 Phase On-Grid", "High Output", "Quote on Request"],
    specs: [
      { label: "Series", value: "SGTU Series (Grid-Tie)" },
      { label: "Model", value: "SGTU-105N" },
      { label: "Rated Output Power", value: "5 kW" },
      { label: "Max DC Input Voltage", value: "500 V" },
      { label: "Startup Voltage", value: "120 V" },
      { label: "MPPT Range", value: "100V - 500V" },
      { label: "Rated AC Output Current", value: "22 A" },
      { label: "Max Efficiency", value: "97.5%" },
    ],
    features: [
      "Dual string capability allows flexible orientation of rooftop arrays",
      "Maximum efficiency up to 97.5%",
      "IP65 enclosure withstands extreme monsoonal downpours and mountain dust",
    ],
    applications: ["Large Villas", "Commercial Showrooms", "Educational Institutions"],
    sourceUrl: "https://poweroneups.com/product/solar-gridtie-invertor",
  },
  {
    id: "power-one-solar-ongrid-6kw",
    name: "Power-One SGTU-106N 6kW Single Phase On-Grid Solar Inverter",
    category: "Power-One Solar",
    subcategory: "On-Grid Inverters",
    brand: "Power-One",
    series: "SGTU Series",
    model: "SGTU-106N",
    capacity: "6 kW",
    price: 0,
    rating: 4.9,
    stock: 15,
    image: "/images/products/power-one/on_grid_4.png",
    images: [
      "/images/products/power-one/on_grid_4.png",
      "/images/products/power-one/on_grid_1.png",
      "/images/products/power-one/on_grid_dropdown.png",
    ],
    tagline: "Top single phase 6 kW on-grid inverter with 26A grid feed capacity.",
    description: "The Power-One SGTU-106N delivers maximum single-phase grid feed-in at 6 kW / 26A. Designed for high-capacity single-phase grid lines with low distortion and comprehensive safety certifications.",
    warranty: "5 Years Manufacturer Warranty",
    badges: ["Power-One Official", "1 Phase On-Grid", "6 kW Max Capacity", "Quote on Request"],
    specs: [
      { label: "Series", value: "SGTU Series (Grid-Tie)" },
      { label: "Model", value: "SGTU-106N" },
      { label: "Rated Output Power", value: "6 kW" },
      { label: "Max DC Input Voltage", value: "500 V" },
      { label: "Startup Voltage", value: "120 V" },
      { label: "MPPT Range", value: "100V - 500V" },
      { label: "Rated AC Output Current", value: "26 A" },
      { label: "Max Efficiency", value: "97.5%" },
    ],
    features: [
      "Full 6 kW power delivery from dual DC strings",
      "Low harmonic current distortion (THD < 3%) ensuring compliance with NEA standards",
      "Smart touch LCD with real-time energy production telemetry",
    ],
    applications: ["Large Residential Estates", "Commercial Buildings", "Warehouses"],
    sourceUrl: "https://poweroneups.com/product/solar-gridtie-invertor",
  },
  {
    id: "power-one-solar-ongrid-3phase-commercial",
    name: "Power-One 3-Phase Commercial On-Grid Solar Inverters (5kW to 35kW)",
    category: "Power-One Solar",
    subcategory: "On-Grid Inverters",
    brand: "Power-One",
    series: "3-Phase Commercial Series",
    model: "Power-One 3P On-Grid (5kW - 35kW)",
    capacity: "5 kW to 35 kW Range",
    price: 0,
    rating: 5.0,
    stock: 12,
    image: "/images/products/power-one/on_grid_3.png",
    images: [
      "/images/products/power-one/on_grid_3.png",
      "/images/products/power-one/on_grid_4.png",
      "/images/products/power-one/on_grid_dropdown.png",
    ],
    tagline: "Commercial 3-phase grid-tie inverters available in 5, 8, 10, 12, 15, 20, 25, 33, and 35 kW.",
    description: "Power-One's commercial 3-phase on-grid solar inverters cover ratings from 5 kW up to 35 kW (5kW, 8kW, 10kW, 12kW, 15kW, 20kW, 25kW, 33kW, 35kW). Built with multiple independent MPPT trackers, wide AC voltage synchronization, and high peak efficiency (>98.4%).",
    warranty: "5 Years Manufacturer Warranty",
    badges: ["Power-One Official", "3 Phase On-Grid", "Multi-MPPT", "Quote on Request"],
    specs: [
      { label: "Series", value: "3-Phase Commercial Grid-Tie" },
      { label: "Available Ratings", value: "5kW, 8kW, 10kW, 12kW, 15kW, 20kW, 25kW, 33kW, 35kW" },
      { label: "Grid Connection", value: "3 Phase / 400VAC (3Ph+N+PE)" },
      { label: "MPPT Trackers", value: "2 to 4 Independent MPPTs" },
      { label: "Max DC Input Voltage", value: "1000 V / 1100 V" },
      { label: "Peak Efficiency", value: "Up to 98.6%" },
      { label: "Protection Degree", value: "IP65 / IP66 Outdoor" },
    ],
    features: [
      "Full coverage for commercial rooftop solar power plants",
      "Multi-MPPT design mitigates partial shading losses",
      "Built-in DC disconnect switch and type II surge arresters",
      "Integrated RS485 and wireless cloud monitoring",
    ],
    applications: ["Commercial Rooftops", "Hospitals", "Hotels & Resorts", "Industrial Plants"],
    sourceUrl: "https://poweroneups.com/product/solar-gridtie-invertor",
  },
  {
    id: "power-one-solar-ongrid-3phase-industrial",
    name: "Power-One 3-Phase Industrial & Utility On-Grid Inverters (40kW to 250kW)",
    category: "Power-One Solar",
    subcategory: "On-Grid Inverters",
    brand: "Power-One",
    series: "3-Phase Industrial Series",
    model: "Power-One Utility Grid-Tie (40kW - 250kW)",
    capacity: "40 kW to 250 kW Range",
    price: 0,
    rating: 5.0,
    stock: 8,
    image: "/images/products/power-one/on_grid_4.png",
    images: [
      "/images/products/power-one/on_grid_4.png",
      "/images/products/power-one/on_grid_3.png",
      "/images/products/power-one/on_grid_dropdown.png",
    ],
    tagline: "Industrial scale 3-phase string inverters: 40kW, 50kW, 60kW, 80kW, 100kW up to 250kW.",
    description: "Power-One's utility-scale 3-phase on-grid solar inverters span from 40 kW to 250 kW (40kW, 50kW, 60kW, 70kW, 75kW, 80kW, 90kW, 100kW, 110kW, 120kW, 136kW, 150kW, 200kW, 250kW). Designed for megawatt-scale solar parks and massive factory rooftops.",
    warranty: "5 Years Manufacturer Warranty",
    badges: ["Power-One Official", "3 Phase Utility", "Up to 250 kW", "Quote on Request"],
    specs: [
      { label: "Series", value: "3-Phase Industrial Grid-Tie" },
      { label: "Available Ratings", value: "40kW, 50kW, 60kW, 70kW, 75kW, 80kW, 90kW, 100kW, 110kW, 120kW, 136kW, 150kW, 200kW, 250kW" },
      { label: "Grid Connection", value: "3 Phase 400V / 480V / 800V" },
      { label: "Max Efficiency", value: "> 98.8%" },
      { label: "MPPT Channels", value: "Up to 12 MPPTs" },
      { label: "Cooling", value: "Intelligent redundant forced air cooling" },
    ],
    features: [
      "Multi-MPPT architecture maximizes generation on complex multi-angle factory roofs",
      "High power density with lightweight design for ease of transport",
      "Anti-PID (Potential Induced Degradation) recovery functionality",
      "Full SCADA compatibility for solar farm remote power curtailment and dispatch",
    ],
    applications: ["Ground-Mounted Solar Farms", "Steel & Cement Factories", "Tea Plantations", "Export Processing Zones"],
    sourceUrl: "https://poweroneups.com/product/solar-gridtie-invertor",
  },

  /* ══════════════════════════════════════════════════════════════════
     4. POWER-ONE SOLAR — HYBRID INVERTERS (1 kW to 250 kW)
     Reference: https://poweroneups.com/product/solar-hybrid-invertor
     ══════════════════════════════════════════════════════════════════ */
  {
    id: "power-one-solar-hybrid-single-phase",
    name: "Power-One Single Phase Solar Hybrid Inverters (1kW to 10kW)",
    category: "Power-One Solar",
    subcategory: "Hybrid Inverters",
    brand: "Power-One",
    series: "Hybrid Series",
    model: "Power-One Hybrid 1P (1kW - 10kW)",
    capacity: "1 kW to 10 kW Range",
    price: 0,
    rating: 4.9,
    stock: 15,
    image: "/images/products/power-one/hybrid_1.png",
    images: [
      "/images/products/power-one/hybrid_1.png",
      "/images/products/power-one/hybrid_2.png",
      "/images/products/power-one/hybrid_3.png",
      "/images/products/power-one/hybrid_dropdown.png",
    ],
    tagline: "Single phase hybrid inverter combining solar generation, battery energy storage, and net metering.",
    description: "Power-One offers single-phase hybrid solar string inverters from 1 kW up to 10 kW. Provides complete net metering capabilities alongside battery backup. Compatible with both tubular deep-cycle and modern Li-ion battery technologies.",
    warranty: "5 Years Manufacturer Warranty",
    badges: ["Power-One Official", "Solar Hybrid", "Storage + Net Metering", "Quote on Request"],
    specs: [
      { label: "Series", value: "Solar Hybrid Series" },
      { label: "Capacity Range", value: "1 kW to 10 kW Single Phase" },
      { label: "Grid Interface", value: "230VAC Single Phase (Net-Metering Ready)" },
      { label: "Battery Compatibility", value: "Lead-Acid Tubular & Lithium-Ion (LiFePO4)" },
      { label: "Operating Modes", value: "Solar-Battery-Grid / Grid-Tied with Storage / Backup UPS" },
      { label: "Switchover Time", value: "< 10 ms seamless transfer" },
    ],
    features: [
      "Enables net metering feed-in while reserving battery capacity for blackout protection",
      "Compatible with all battery chemistries including Tall Tubular and Lithium-Ion",
      "Transformer-less and transformer-based options depending on customer load profiles",
      "User-friendly 7\" colour touch display with comprehensive event recording",
    ],
    applications: ["Residential Energy Independence", "Small Commercial Businesses", "Clinics & Pharmacies"],
    sourceUrl: "https://poweroneups.com/product/solar-hybrid-invertor",
  },
  {
    id: "power-one-solar-hybrid-three-phase",
    name: "Power-One Three Phase Industrial Solar Hybrid Inverters (10kW to 250kW)",
    category: "Power-One Solar",
    subcategory: "Hybrid Inverters",
    brand: "Power-One",
    series: "Hybrid Series",
    model: "Power-One Hybrid 3P (10kW - 250kW)",
    capacity: "10 kW to 250 kW Range",
    price: 0,
    rating: 5.0,
    stock: 6,
    image: "/images/products/power-one/hybrid_3.png",
    images: [
      "/images/products/power-one/hybrid_3.png",
      "/images/products/power-one/hybrid_4.png",
      "/images/products/power-one/hybrid_5.png",
      "/images/products/power-one/hybrid_dropdown.png",
    ],
    tagline: "Three-phase commercial & industrial hybrid string inverters from 10 kW up to 250 kW.",
    description: "Power-One offers the industry's widest range of hybrid string inverters up to 250 kW. Supports three-phase grid-tied net metering combined with high-voltage battery storage banks (BESS). Tailored for commercial, industrial, and government buildings requiring peak-shaving and zero-interruption backup.",
    warranty: "5 Years Manufacturer Warranty",
    badges: ["Power-One Official", "3 Phase Hybrid", "Up to 250 kW", "Quote on Request"],
    specs: [
      { label: "Series", value: "Solar Hybrid Series" },
      { label: "Capacity Range", value: "10 kW to 250 kW Three Phase" },
      { label: "Grid Interface", value: "400VAC / 415VAC 3-Phase" },
      { label: "Battery Chemistry", value: "High-Voltage LiFePO4 & Industrial Lead-Acid" },
      { label: "Topology", value: "Transformer-based and Transformer-less available" },
    ],
    features: [
      "Industry-leading 250 kW hybrid power rating with synchronized BESS storage",
      "Peak shaving, time-of-use tariff optimization, and microgrid black-start capability",
      "Dual grid & diesel generator interface with automatic load balancing",
    ],
    applications: ["Commercial & Industrial Complexes", "Government Buildings", "Off-Grid Island / Himalayan Microgrids"],
    sourceUrl: "https://poweroneups.com/product/solar-hybrid-invertor",
  },

  /* ══════════════════════════════════════════════════════════════════
     5. POWER-ONE SOLAR — OFF-GRID INVERTERS
     Reference: https://poweroneups.com/product/solar-offgrid-invertor
     ══════════════════════════════════════════════════════════════════ */
  {
    id: "power-one-solar-offgrid-single-phase",
    name: "Power-One Single Phase Rugged Off-Grid Solar Inverter (1kVA to 10kVA)",
    category: "Power-One Solar",
    subcategory: "Off-Grid Inverters",
    brand: "Power-One",
    series: "Off-Grid Series",
    model: "Power-One Off-Grid 1P",
    capacity: "1 kVA to 10 kVA Range",
    price: 0,
    rating: 4.8,
    stock: 18,
    image: "/images/products/power-one/offgrid_inverter.png",
    images: [
      "/images/products/power-one/offgrid_inverter.png",
      "/images/products/power-one/solar_inverter.png",
      "/images/products/power-one/offgrid_dropdown.png",
    ],
    tagline: "Rugged standalone off-grid solar inverter with high MPPT efficiency and auto-bypass.",
    description: "Power-One offers the industry's oldest and most rugged off-grid systems. Designed for areas without utility grid connection, widely exported to African nations and remote environments. Features wide input voltage range, high MPPT charge efficiency, grid charging option, and automatic bypass.",
    warranty: "2 Years Manufacturer Warranty",
    badges: ["Power-One Official", "Off-Grid", "Heavy Duty", "Quote on Request"],
    specs: [
      { label: "Series", value: "Off-Grid Series" },
      { label: "Capacity Range", value: "1 kVA to 10 kVA Single Phase" },
      { label: "Output Voltage", value: "230VAC Pure Sine Wave (±1%)" },
      { label: "Charge Controller", value: "High-efficiency MPPT built-in" },
      { label: "Input Window", value: "Wide solar and auxiliary input voltage range" },
      { label: "Features", value: "Auto-bypass & optional grid/generator charging" },
    ],
    features: [
      "Industry's most rugged standalone architecture engineered for zero-grid regions",
      "Integrated high-efficiency MPPT solar charge controller",
      "Auto-bypass feature and multi-mode charging from auxiliary generator",
      "Proven field reliability across extreme climates and non-electrified territories",
    ],
    applications: ["Remote Mountain Lodges", "Off-Grid Farmhouses", "Telecommunication Base Stations", "Rural Schools"],
    sourceUrl: "https://poweroneups.com/product/solar-offgrid-invertor",
  },
  {
    id: "power-one-solar-offgrid-three-phase",
    name: "Power-One Three Phase Industrial Off-Grid Solar Power Inverter (10kVA to 100kVA)",
    category: "Power-One Solar",
    subcategory: "Off-Grid Inverters",
    brand: "Power-One",
    series: "Off-Grid Series",
    model: "Power-One Off-Grid 3P",
    capacity: "10 kVA to 100 kVA Range",
    price: 0,
    rating: 5.0,
    stock: 5,
    image: "/images/products/power-one/offgrid_inverter.png",
    images: [
      "/images/products/power-one/offgrid_inverter.png",
      "/images/products/power-one/solar_inverter.png",
      "/images/products/power-one/offgrid_dropdown.png",
    ],
    tagline: "Heavy three-phase off-grid power generation system for off-grid communities and resorts.",
    description: "The Power-One Three Phase Off-Grid system delivers 10 kVA to 100 kVA of pure three-phase power in standalone environments. Incorporates industrial copper isolation transformers, high-capacity MPPT arrays, and diesel generator synchronizing logic.",
    warranty: "2 Years Manufacturer Warranty",
    badges: ["Power-One Official", "3 Phase Off-Grid", "Industrial Microgrid", "Quote on Request"],
    specs: [
      { label: "Series", value: "Off-Grid Series" },
      { label: "Capacity Range", value: "10 kVA to 100 kVA Three Phase" },
      { label: "Output Voltage", value: "400VAC / 415VAC (3Ph+N)" },
      { label: "Isolation", value: "Heavy-duty galvanic isolation transformer" },
      { label: "Solar Controller", value: "Integrated high-voltage MPPT array" },
    ],
    features: [
      "Powers heavy 3-phase machinery, water pumps, and refrigeration without grid power",
      "Intelligent priority sequencing: Solar → Battery → Auxiliary Generator",
      "Heavy-duty sheet steel enclosure with thermal ventilation channels",
    ],
    applications: ["Eco Resorts & Safari Lodges", "Remote Mining Camps", "Isolated Village Microgrids", "Agricultural Processing Centers"],
    sourceUrl: "https://poweroneups.com/product/solar-offgrid-invertor",
  },

  /* ══════════════════════════════════════════════════════════════════
     6. POWER-ONE SOLAR — POWER SOLUTIONS / SOLAR EPC
     Reference: https://poweroneups.com/product/solar-power-solutions
     ══════════════════════════════════════════════════════════════════ */
  {
    id: "power-one-solar-offgrid-rooftop-system",
    name: "Power-One Off-Grid Rooftop Solar PV Systems (500W to 100kW)",
    category: "Power-One Solar",
    subcategory: "Solar Power Solutions",
    brand: "Power-One",
    series: "Solar Power Solutions",
    model: "Off-Grid Rooftop PV (500W - 100kW)",
    capacity: "500W to 100 kW System Range",
    price: 0,
    rating: 4.9,
    stock: 10,
    image: "/images/products/power-one/solar_install.png",
    images: [
      "/images/products/power-one/solar_install.png",
      "/images/products/power-one/power_plant.jpg",
    ],
    tagline: "Turnkey standalone photovoltaic systems with battery storage for homes and remote infrastructure.",
    description: "An off-grid standalone photovoltaic system producing self-generated electricity from solar energy with dedicated battery banks. The load is fed directly from solar with priority; excess solar charges batteries. When solar is unavailable, loads are powered seamlessly from the battery bank or auxiliary generator.",
    warranty: "5 Years System / 25 Years Panel Performance Warranty",
    badges: ["Power-One Official", "Solar EPC Solution", "500W to 100kW", "Quote on Request"],
    specs: [
      { label: "System Type", value: "Off-Grid Rooftop Photovoltaic System" },
      { label: "Capacity Range", value: "500W to 100 kW" },
      { label: "Priority Logic", value: "Solar → Battery → Auxiliary Mains / Gen" },
      { label: "Storage Technology", value: "Deep Cycle Tubular / LiFePO4 Lithium" },
      { label: "Mounting Structure", value: "Hot-dip galvanized anodized aluminum" },
    ],
    features: [
      "Produces independent electricity via high-efficiency PV arrays with no moving parts",
      "Excess solar energy automatically channeled to battery replenishment",
      "Custom engineered for Nepal's mountainous topography and power cut realities",
      "Full turnkey installation by OMSUN licensed solar EPC engineers",
    ],
    applications: ["Off-Grid Residences", "Tea Estates", "Himalayan Tourism Lodges", "Border Outposts"],
    sourceUrl: "https://poweroneups.com/product/solar-power-solutions",
  },
  {
    id: "power-one-solar-ongrid-rooftop-system",
    name: "Power-One On-Grid / Grid-Tie Solar PV Systems (3kW to 500kW)",
    category: "Power-One Solar",
    subcategory: "Solar Power Solutions",
    brand: "Power-One",
    series: "Solar Power Solutions",
    model: "On-Grid Rooftop PV (3kW - 500kW)",
    capacity: "3 kW to 500 kW System Range",
    price: 0,
    rating: 5.0,
    stock: 15,
    image: "/images/products/power-one/power_plant.jpg",
    images: [
      "/images/products/power-one/power_plant.jpg",
      "/images/products/power-one/solar_install.png",
    ],
    tagline: "Turnkey rooftop on-grid solar solutions with NEA bi-directional net-metering integration.",
    description: "Power-One On-Grid rooftop solar systems connect directly to the utility electrical network. Solar electricity directly powers your daytime loads, with excess generated units pushed back into the national grid through NEA bi-directional net metering.",
    warranty: "5 Years System / 25 Years Panel Performance Warranty",
    badges: ["Power-One Official", "Turnkey Solar EPC", "NEA Net-Metering", "Quote on Request"],
    specs: [
      { label: "System Type", value: "Grid-Tied Photovoltaic Power Plant" },
      { label: "Capacity Range", value: "3 kW to 500 kW" },
      { label: "Net Metering", value: "Full NEA Bi-directional coordination" },
      { label: "Inverters", value: "Power-One SGTU Single/Three-Phase string inverters" },
      { label: "Panels", value: "Tier-1 N-Type TOPCon / Mono PERC modules" },
    ],
    features: [
      "Lowers daytime utility electricity bills by up to 85%",
      "Complete 3D shadow analysis, engineering SLD design, and NEA paper filing handled",
      "Real-time mobile app and cloud generation telemetry",
    ],
    applications: ["Commercial Buildings", "Manufacturing Factories", "Schools & Colleges", "Hospitals"],
    sourceUrl: "https://poweroneups.com/product/solar-power-solutions",
  },
  {
    id: "power-one-solar-pump-solution",
    name: "Power-One Turnkey Solar Water Pumping Solutions (1 HP to 50 HP)",
    category: "Power-One Solar",
    subcategory: "Solar Pump / Controllers",
    brand: "Power-One",
    series: "Solar Pump Solutions",
    model: "Solar Pump System (1HP - 50HP)",
    capacity: "1 HP to 50 HP Pump Systems",
    price: 0,
    rating: 4.9,
    stock: 12,
    image: "/images/products/power-one/solar_install.png",
    images: [
      "/images/products/power-one/solar_install.png",
      "/images/products/power-one/power_plant.jpg",
    ],
    tagline: "Zero-fuel agricultural and community water pumping powered directly by solar PV.",
    description: "Power-One Solar Water Pumping systems utilize direct current generated from solar arrays to drive AC three-phase submersible or monoblock water pumps. Eliminates costly diesel generators and erratic grid electricity for agricultural irrigation, community drinking supply, and industrial pumping.",
    warranty: "5 Years Manufacturer Warranty",
    badges: ["Power-One Official", "Solar Water Pump", "Zero Fuel", "Quote on Request"],
    specs: [
      { label: "Application", value: "Agricultural & Drinking Water Pumping" },
      { label: "Horsepower Range", value: "1 HP to 50 HP" },
      { label: "Pump Type Supported", value: "Submersible Borewell, Monoblock, Surface Pumps" },
      { label: "Drive Mechanism", value: "Variable Frequency Drive (VFD) with MPPT" },
      { label: "Grid Hybrid Option", value: "Dual input: accepts 3-phase AC grid or generator" },
    ],
    features: [
      "Generates electricity from sunlight with no moving or wearing parts",
      "Maximizes water delivery during early morning and late afternoon via dynamic MPPT",
      "Can accept three-phase AC input from grid/generator when solar is unavailable",
      "Automatic dry-run protection, motor overload protection, and tank full cutoff",
    ],
    applications: ["Agricultural Irrigation", "Community Drinking Water Projects", "Fish Farming & Hatcheries", "Rural Resorts"],
    sourceUrl: "https://poweroneups.com/product/solar-power-solutions",
  },
  {
    id: "power-one-solar-pump-controller",
    name: "Power-One Variable Speed MPPT Solar Pump Controller",
    category: "Power-One Solar",
    subcategory: "Solar Pump / Controllers",
    brand: "Power-One",
    series: "Solar Pump Solutions",
    model: "Power-One Solar Pump Drive",
    capacity: "1 HP to 50 HP AC Drives",
    price: 0,
    rating: 5.0,
    stock: 16,
    image: "/images/products/power-one/solar_install.png",
    images: [
      "/images/products/power-one/solar_install.png",
      "/images/products/power-one/offgrid_inverter.png",
    ],
    tagline: "Rugged powder-coated MS enclosure MPPT solar pump drive for 3-phase AC pumps.",
    description: "The Power-One Solar Pump Controller is housed in a rugged powder-coated mild steel (MS) enclosure. Designed with high-speed MPPT technology to convert variable DC from solar panels into variable-frequency 3-phase AC to run any standard AC pump at proportional speeds.",
    warranty: "3 Years Manufacturer Warranty",
    badges: ["Power-One Official", "MPPT Pump Drive", "Rugged Enclosure", "Quote on Request"],
    specs: [
      { label: "Enclosure", value: "Powder-coated rugged MS industrial enclosure" },
      { label: "Compatible Motors", value: "Any standard 3-phase AC induction or PMSM pump" },
      { label: "Control Algorithm", value: "Sensorless Vector VFD with dynamic solar MPPT" },
      { label: "Dual Input Support", value: "Solar DC + 3-Phase AC Grid/Gen with auto-changeover" },
      { label: "Operating Efficiency", value: "> 98%" },
    ],
    features: [
      "Can be used on any AC 3-phase pump, whether monoblock or submersible",
      "Designed with MPPT technology to maximize water delivery at varying solar irradiances",
      "Runs pump at full speed when sunlight is abundant, and lower speed during cloudy periods",
      "Built-in lightning, surge, dry run, and phase loss protections",
    ],
    applications: ["Farmer Irrigation Cooperatives", "Borewell Water Lifting", "Municipal Lift Irrigation"],
    sourceUrl: "https://poweroneups.com/product/solar-power-solutions",
  },
];
