/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SolarSolutionsRouteImport } from './routes/solar-solutions'
import { Route as WhyOmsunRouteImport } from './routes/why-omsun'
import { Route as AdminAdminDashboardRouteImport } from './routes/_admin.admin-dashboard'
import { Route as ProtectedCheckoutRouteImport } from './routes/_protected.checkout'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected.dashboard'
import { Route as ProductIdRouteImport } from './routes/product.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SolarSolutionsRoute = SolarSolutionsRouteImport.update({
  id: '/solar-solutions',
  path: '/solar-solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const WhyOmsunRoute = WhyOmsunRouteImport.update({
  id: '/why-omsun',
  path: '/why-omsun',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminDashboardRoute = AdminAdminDashboardRouteImport.update({
  id: '/admin-dashboard',
  path: '/admin-dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const ProtectedCheckoutRoute = ProtectedCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/projects': typeof ProjectsRoute
  '/shop': typeof ShopRoute
  '/solar-solutions': typeof SolarSolutionsRoute
  '/why-omsun': typeof WhyOmsunRoute
  '/admin-dashboard': typeof AdminAdminDashboardRoute
  '/checkout': typeof ProtectedCheckoutRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/product/$id': typeof ProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/projects': typeof ProjectsRoute
  '/shop': typeof ShopRoute
  '/solar-solutions': typeof SolarSolutionsRoute
  '/why-omsun': typeof WhyOmsunRoute
  '/admin-dashboard': typeof AdminAdminDashboardRoute
  '/checkout': typeof ProtectedCheckoutRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/product/$id': typeof ProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_protected': typeof ProtectedRouteWithChildren
  '/auth': typeof AuthRoute
  '/projects': typeof ProjectsRoute
  '/shop': typeof ShopRoute
  '/solar-solutions': typeof SolarSolutionsRoute
  '/why-omsun': typeof WhyOmsunRoute
  '/_admin/admin-dashboard': typeof AdminAdminDashboardRoute
  '/_protected/checkout': typeof ProtectedCheckoutRoute
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/product/$id': typeof ProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/projects'
    | '/shop'
    | '/solar-solutions'
    | '/why-omsun'
    | '/admin-dashboard'
    | '/checkout'
    | '/dashboard'
    | '/product/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/projects'
    | '/shop'
    | '/solar-solutions'
    | '/why-omsun'
    | '/admin-dashboard'
    | '/checkout'
    | '/dashboard'
    | '/product/$id'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_protected'
    | '/auth'
    | '/projects'
    | '/shop'
    | '/solar-solutions'
    | '/why-omsun'
    | '/_admin/admin-dashboard'
    | '/_protected/checkout'
    | '/_protected/dashboard'
    | '/product/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ProtectedRoute: typeof ProtectedRouteWithChildren
  AuthRoute: typeof AuthRoute
  ProjectsRoute: typeof ProjectsRoute
  ShopRoute: typeof ShopRoute
  SolarSolutionsRoute: typeof SolarSolutionsRoute
  WhyOmsunRoute: typeof WhyOmsunRoute
  ProductIdRoute: typeof ProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solar-solutions': {
      id: '/solar-solutions'
      path: '/solar-solutions'
      fullPath: '/solar-solutions'
      preLoaderRoute: typeof SolarSolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/why-omsun': {
      id: '/why-omsun'
      path: '/why-omsun'
      fullPath: '/why-omsun'
      preLoaderRoute: typeof WhyOmsunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/admin-dashboard': {
      id: '/_admin/admin-dashboard'
      path: '/admin-dashboard'
      fullPath: '/admin-dashboard'
      preLoaderRoute: typeof AdminAdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_protected/checkout': {
      id: '/_protected/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof ProtectedCheckoutRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAdminDashboardRoute: typeof AdminAdminDashboardRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminDashboardRoute: AdminAdminDashboardRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ProtectedRouteChildren {
  ProtectedCheckoutRoute: typeof ProtectedCheckoutRoute
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedCheckoutRoute: ProtectedCheckoutRoute,
  ProtectedDashboardRoute: ProtectedDashboardRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ProtectedRoute: ProtectedRouteWithChildren,
  AuthRoute: AuthRoute,
  ProjectsRoute: ProjectsRoute,
  ShopRoute: ShopRoute,
  SolarSolutionsRoute: SolarSolutionsRoute,
  WhyOmsunRoute: WhyOmsunRoute,
  ProductIdRoute: ProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
